"""Add ETLExecution model

Revision ID: 6e76fc1483fa
Revises: update_actividades_uuid
Create Date: 2025-11-20 23:28:49.859213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e76fc1483fa'
down_revision = 'update_actividades_uuid'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etl_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'CANCELLED', name='etlstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('records_extracted', sa.Integer(), nullable=False),
    sa.Column('records_transformed', sa.Integer(), nullable=False),
    sa.Column('records_loaded', sa.Integer(), nullable=False),
    sa.Column('records_failed', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('log_file_path', sa.String(length=500), nullable=True),
    sa.Column('triggered_by', sa.String(length=100), nullable=False),
    sa.Column('config', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etl_executions_id'), 'etl_executions', ['id'], unique=False)
    op.create_index(op.f('ix_etl_executions_source'), 'etl_executions', ['source'], unique=False)
    op.create_index(op.f('ix_etl_executions_status'), 'etl_executions', ['status'], unique=False)
    op.add_column('favoritos', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('favoritos', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_constraint('favoritos_actividad_id_fkey', 'favoritos', type_='foreignkey')
    op.drop_constraint('favoritos_usuario_id_fkey', 'favoritos', type_='foreignkey')
    op.create_foreign_key(None, 'favoritos', 'actividades', ['actividad_id'], ['id'])
    op.create_foreign_key(None, 'favoritos', 'usuarios', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favoritos', type_='foreignkey')
    op.drop_constraint(None, 'favoritos', type_='foreignkey')
    op.create_foreign_key('favoritos_usuario_id_fkey', 'favoritos', 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('favoritos_actividad_id_fkey', 'favoritos', 'actividades', ['actividad_id'], ['id'], ondelete='CASCADE')
    op.drop_column('favoritos', 'updated_at')
    op.drop_column('favoritos', 'created_at')
    op.drop_index(op.f('ix_etl_executions_status'), table_name='etl_executions')
    op.drop_index(op.f('ix_etl_executions_source'), table_name='etl_executions')
    op.drop_index(op.f('ix_etl_executions_id'), table_name='etl_executions')
    op.drop_table('etl_executions')
    # ### end Alembic commands ###
