"""Initial Migration: usuarios, perfiles, actividades, favoritos

Revision ID: 3ff96ba0ec7a
Revises: 
Create Date: 2025-10-21 20:16:35.048410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ff96ba0ec7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actividades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('tipo', sa.Enum('CULTURAL', 'DEPORTIVA', 'RECREATIVA', 'EDUCATIVA', 'SOCIAL', name='tipoactividad'), nullable=False),
    sa.Column('localidad', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=500), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('hora_inicio', sa.Time(), nullable=True),
    sa.Column('hora_fin', sa.Time(), nullable=True),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('capacidad_maxima', sa.Integer(), nullable=True),
    sa.Column('etiquetas', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('estado', sa.Enum('ACTIVA', 'PENDIENTE', 'FINALIZADA', 'CANCELADA', name='estadoactividad'), nullable=False),
    sa.Column('organizador', sa.String(length=255), nullable=True),
    sa.Column('contacto_email', sa.String(length=255), nullable=True),
    sa.Column('contacto_telefono', sa.String(length=20), nullable=True),
    sa.Column('url_externa', sa.String(length=500), nullable=True),
    sa.Column('imagen_url', sa.String(length=500), nullable=True),
    sa.Column('popularidad', sa.Float(), nullable=False),
    sa.Column('vistas', sa.Integer(), nullable=False),
    sa.Column('fuente', sa.String(length=50), nullable=False),
    sa.Column('validado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actividades_estado'), 'actividades', ['estado'], unique=False)
    op.create_index(op.f('ix_actividades_etiquetas'), 'actividades', ['etiquetas'], unique=False)
    op.create_index(op.f('ix_actividades_fecha_inicio'), 'actividades', ['fecha_inicio'], unique=False)
    op.create_index(op.f('ix_actividades_id'), 'actividades', ['id'], unique=False)
    op.create_index(op.f('ix_actividades_localidad'), 'actividades', ['localidad'], unique=False)
    op.create_index(op.f('ix_actividades_popularidad'), 'actividades', ['popularidad'], unique=False)
    op.create_index(op.f('ix_actividades_tipo'), 'actividades', ['tipo'], unique=False)
    op.create_index(op.f('ix_actividades_titulo'), 'actividades', ['titulo'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('actividad_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actividad_id'], ['actividades.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'actividad_id', name='uq_usuario_actividad')
    )
    op.create_index(op.f('ix_favoritos_actividad_id'), 'favoritos', ['actividad_id'], unique=False)
    op.create_index(op.f('ix_favoritos_id'), 'favoritos', ['id'], unique=False)
    op.create_index(op.f('ix_favoritos_usuario_id'), 'favoritos', ['usuario_id'], unique=False)
    op.create_table('perfiles_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('biografia', sa.Text(), nullable=True),
    sa.Column('etiquetas_interes', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('localidad_preferida', sa.String(length=100), nullable=True),
    sa.Column('disponibilidad_horaria', sa.String(length=50), nullable=True),
    sa.Column('nivel_actividad', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_index(op.f('ix_perfiles_usuario_id'), 'perfiles_usuario', ['id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_perfiles_usuario_id'), table_name='perfiles_usuario')
    op.drop_table('perfiles_usuario')
    op.drop_index(op.f('ix_favoritos_usuario_id'), table_name='favoritos')
    op.drop_index(op.f('ix_favoritos_id'), table_name='favoritos')
    op.drop_index(op.f('ix_favoritos_actividad_id'), table_name='favoritos')
    op.drop_table('favoritos')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_actividades_titulo'), table_name='actividades')
    op.drop_index(op.f('ix_actividades_tipo'), table_name='actividades')
    op.drop_index(op.f('ix_actividades_popularidad'), table_name='actividades')
    op.drop_index(op.f('ix_actividades_localidad'), table_name='actividades')
    op.drop_index(op.f('ix_actividades_id'), table_name='actividades')
    op.drop_index(op.f('ix_actividades_fecha_inicio'), table_name='actividades')
    op.drop_index(op.f('ix_actividades_etiquetas'), table_name='actividades')
    op.drop_index(op.f('ix_actividades_estado'), table_name='actividades')
    op.drop_table('actividades')
    # ### end Alembic commands ###
