/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RegisterImport } from './routes/register'
import { Route as RecomendacionesImport } from './routes/recomendaciones'
import { Route as PerfilImport } from './routes/perfil'
import { Route as LoginImport } from './routes/login'
import { Route as FavoritosImport } from './routes/favoritos'
import { Route as AdminImport } from './routes/admin'
import { Route as ActividadesImport } from './routes/actividades'
import { Route as IndexImport } from './routes/index'
import { Route as AdminIndexImport } from './routes/admin.index'
import { Route as AdminEtlImport } from './routes/admin.etl'
import { Route as AdminDashboardImport } from './routes/admin.dashboard'
import { Route as AdminActividadesImport } from './routes/admin.actividades'
import { Route as ActividadesIdImport } from './routes/actividades.$id'
import { Route as AdminActividadesPendientesImport } from './routes/admin.actividades.pendientes'

// Create/Update Routes

const RegisterRoute = RegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const RecomendacionesRoute = RecomendacionesImport.update({
  id: '/recomendaciones',
  path: '/recomendaciones',
  getParentRoute: () => rootRoute,
} as any)

const PerfilRoute = PerfilImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const FavoritosRoute = FavoritosImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRoute,
} as any)

const AdminRoute = AdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const ActividadesRoute = ActividadesImport.update({
  id: '/actividades',
  path: '/actividades',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)

const AdminEtlRoute = AdminEtlImport.update({
  id: '/etl',
  path: '/etl',
  getParentRoute: () => AdminRoute,
} as any)

const AdminDashboardRoute = AdminDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)

const AdminActividadesRoute = AdminActividadesImport.update({
  id: '/actividades',
  path: '/actividades',
  getParentRoute: () => AdminRoute,
} as any)

const ActividadesIdRoute = ActividadesIdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ActividadesRoute,
} as any)

const AdminActividadesPendientesRoute = AdminActividadesPendientesImport.update(
  {
    id: '/pendientes',
    path: '/pendientes',
    getParentRoute: () => AdminActividadesRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/actividades': {
      id: '/actividades'
      path: '/actividades'
      fullPath: '/actividades'
      preLoaderRoute: typeof ActividadesImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilImport
      parentRoute: typeof rootRoute
    }
    '/recomendaciones': {
      id: '/recomendaciones'
      path: '/recomendaciones'
      fullPath: '/recomendaciones'
      preLoaderRoute: typeof RecomendacionesImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/actividades/$id': {
      id: '/actividades/$id'
      path: '/$id'
      fullPath: '/actividades/$id'
      preLoaderRoute: typeof ActividadesIdImport
      parentRoute: typeof ActividadesImport
    }
    '/admin/actividades': {
      id: '/admin/actividades'
      path: '/actividades'
      fullPath: '/admin/actividades'
      preLoaderRoute: typeof AdminActividadesImport
      parentRoute: typeof AdminImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardImport
      parentRoute: typeof AdminImport
    }
    '/admin/etl': {
      id: '/admin/etl'
      path: '/etl'
      fullPath: '/admin/etl'
      preLoaderRoute: typeof AdminEtlImport
      parentRoute: typeof AdminImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof AdminImport
    }
    '/admin/actividades/pendientes': {
      id: '/admin/actividades/pendientes'
      path: '/pendientes'
      fullPath: '/admin/actividades/pendientes'
      preLoaderRoute: typeof AdminActividadesPendientesImport
      parentRoute: typeof AdminActividadesImport
    }
  }
}

// Create and export the route tree

interface ActividadesRouteChildren {
  ActividadesIdRoute: typeof ActividadesIdRoute
}

const ActividadesRouteChildren: ActividadesRouteChildren = {
  ActividadesIdRoute: ActividadesIdRoute,
}

const ActividadesRouteWithChildren = ActividadesRoute._addFileChildren(
  ActividadesRouteChildren,
)

interface AdminActividadesRouteChildren {
  AdminActividadesPendientesRoute: typeof AdminActividadesPendientesRoute
}

const AdminActividadesRouteChildren: AdminActividadesRouteChildren = {
  AdminActividadesPendientesRoute: AdminActividadesPendientesRoute,
}

const AdminActividadesRouteWithChildren =
  AdminActividadesRoute._addFileChildren(AdminActividadesRouteChildren)

interface AdminRouteChildren {
  AdminActividadesRoute: typeof AdminActividadesRouteWithChildren
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEtlRoute: typeof AdminEtlRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActividadesRoute: AdminActividadesRouteWithChildren,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEtlRoute: AdminEtlRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actividades': typeof ActividadesRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/recomendaciones': typeof RecomendacionesRoute
  '/register': typeof RegisterRoute
  '/actividades/$id': typeof ActividadesIdRoute
  '/admin/actividades': typeof AdminActividadesRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/etl': typeof AdminEtlRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/actividades/pendientes': typeof AdminActividadesPendientesRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actividades': typeof ActividadesRouteWithChildren
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/recomendaciones': typeof RecomendacionesRoute
  '/register': typeof RegisterRoute
  '/actividades/$id': typeof ActividadesIdRoute
  '/admin/actividades': typeof AdminActividadesRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/etl': typeof AdminEtlRoute
  '/admin': typeof AdminIndexRoute
  '/admin/actividades/pendientes': typeof AdminActividadesPendientesRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/actividades': typeof ActividadesRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/recomendaciones': typeof RecomendacionesRoute
  '/register': typeof RegisterRoute
  '/actividades/$id': typeof ActividadesIdRoute
  '/admin/actividades': typeof AdminActividadesRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/etl': typeof AdminEtlRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/actividades/pendientes': typeof AdminActividadesPendientesRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actividades'
    | '/admin'
    | '/favoritos'
    | '/login'
    | '/perfil'
    | '/recomendaciones'
    | '/register'
    | '/actividades/$id'
    | '/admin/actividades'
    | '/admin/dashboard'
    | '/admin/etl'
    | '/admin/'
    | '/admin/actividades/pendientes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actividades'
    | '/favoritos'
    | '/login'
    | '/perfil'
    | '/recomendaciones'
    | '/register'
    | '/actividades/$id'
    | '/admin/actividades'
    | '/admin/dashboard'
    | '/admin/etl'
    | '/admin'
    | '/admin/actividades/pendientes'
  id:
    | '__root__'
    | '/'
    | '/actividades'
    | '/admin'
    | '/favoritos'
    | '/login'
    | '/perfil'
    | '/recomendaciones'
    | '/register'
    | '/actividades/$id'
    | '/admin/actividades'
    | '/admin/dashboard'
    | '/admin/etl'
    | '/admin/'
    | '/admin/actividades/pendientes'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActividadesRoute: typeof ActividadesRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  FavoritosRoute: typeof FavoritosRoute
  LoginRoute: typeof LoginRoute
  PerfilRoute: typeof PerfilRoute
  RecomendacionesRoute: typeof RecomendacionesRoute
  RegisterRoute: typeof RegisterRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActividadesRoute: ActividadesRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  FavoritosRoute: FavoritosRoute,
  LoginRoute: LoginRoute,
  PerfilRoute: PerfilRoute,
  RecomendacionesRoute: RecomendacionesRoute,
  RegisterRoute: RegisterRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/actividades",
        "/admin",
        "/favoritos",
        "/login",
        "/perfil",
        "/recomendaciones",
        "/register"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/actividades": {
      "filePath": "actividades.tsx",
      "children": [
        "/actividades/$id"
      ]
    },
    "/admin": {
      "filePath": "admin.tsx",
      "children": [
        "/admin/actividades",
        "/admin/dashboard",
        "/admin/etl",
        "/admin/"
      ]
    },
    "/favoritos": {
      "filePath": "favoritos.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/perfil": {
      "filePath": "perfil.tsx"
    },
    "/recomendaciones": {
      "filePath": "recomendaciones.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/actividades/$id": {
      "filePath": "actividades.$id.tsx",
      "parent": "/actividades"
    },
    "/admin/actividades": {
      "filePath": "admin.actividades.tsx",
      "parent": "/admin",
      "children": [
        "/admin/actividades/pendientes"
      ]
    },
    "/admin/dashboard": {
      "filePath": "admin.dashboard.tsx",
      "parent": "/admin"
    },
    "/admin/etl": {
      "filePath": "admin.etl.tsx",
      "parent": "/admin"
    },
    "/admin/": {
      "filePath": "admin.index.tsx",
      "parent": "/admin"
    },
    "/admin/actividades/pendientes": {
      "filePath": "admin.actividades.pendientes.tsx",
      "parent": "/admin/actividades"
    }
  }
}
ROUTE_MANIFEST_END */
